version: "3.7"

services:
        app:
                image: britton13lee/blabber
                environment:
                        FLASK_ENV: development
                        DEBUG_METRICS: "true"
                deploy:
                    replicas: 2
                    labels:
                        - traefik.http.routers.app.rule=PathPrefix(`/api`)
                        - traefik.http.middlewares.strip-api-prefix.stripprefix.prefixes=/api
                        - traefik.http.routers.app.middlewares=strip-api-prefix
                        - traefik.http.services.flask.loadbalancer.server.port=5000
                    placement:
                        constraints:
                            - "node.role==worker"
                                      
        frontend:
                image: vtcs2304s19/blabber-client
                deploy:
                    replicas: 2
                    labels:
                        - traefik.http.routers.frontend.rule=PathPrefix(`/`)
                    placement:
                        constraints:
                            - "node.role==worker"
                    
        proxy:
                image: traefik:v2.1
                command: --api.insecure=true --providers.docker --providers.docker.swarmMode=true
                ports:
                        - 80:80
                        - 8080:8080
                volumes:
                        - /var/run/docker.sock:/var/run/docker.sock
                deploy:
                    placement:
                        constraints:
                        - "node.role==manager"
                      

        mongo:
                image: mongo
                volumes: 
                        - mongo-data:/data/db
                deploy:
                    placement:
                        constraints:
                        - "node.role==worker"
                      

        prometheus:
                image: prom/prometheus
                ports:
                        - 9090:9090
                volumes:
                        - ./prometheus.yml:/etc/prometheus/prometheus.yml

        grafana:
                image: grafana/grafana
                volumes:
                        - grafana-storage:/var/lib/grafana
                ports:
                        - 3000:3000
volumes:
    mongo-data:
    grafana-storage: